
export const DEFAULT_CONTRACT_TEMPLATE = `
This Exclusive Music Publishing Agreement ("Agreement") is made and entered into as of [SUBMISSION_DATE] ("Effective Date"), by and between Sap Media Publishing ("Publisher") and [SUBMITTER_NAME] on behalf of all contributing writers ("Writer").

RECITALS

WHEREAS, Writer is a professional writer, composer, and author of musical compositions; and
WHEREAS, Publisher is in the business of music publishing, promotion, and administration; and
WHEREAS, Writer desires to grant to Publisher the exclusive right to administer and publish the musical composition currently entitled "[SONG_TITLE]" (the "Composition"), as performed by [ARTIST_NAMES].

NOW, THEREFORE, in consideration of the mutual covenants and promises hereinafter set forth, the parties agree as follows:

1. Grant of Rights.
Writer hereby irrevocably and exclusively assigns, conveys, and grants to Publisher, its successors, and assigns, for the full term of copyright and all renewals and extensions thereof, all rights and interests of every kind and nature in and to the Composition, including but not to the worldwide copyright thereof, the right to secure copyright registration, and all other rights now or hereafter known or existing, including but not to:
(a) The exclusive right to print, publish, sell, and distribute sheet music and other printed forms of the Composition.
(b) The exclusive right to license, control, and collect all income from the mechanical reproduction of the Composition.
(c) The exclusive right to license the public performance of the Composition for profit.
(d) The exclusive right to license the synchronization of the Composition with motion pictures, television programs, and other audiovisual works.

2. Royalties.
Publisher shall pay to Writer a sum equal to fifty percent (50%) of the Net Income actually received by Publisher in the United States from the exploitation of the rights granted herein. "Net Income" is defined as the gross receipts received by Publisher less all customary and reasonable expenses. The remaining fifty percent (50%) shall be retained by the Publisher as its administration fee.

3. Term.
The term of this Agreement shall be for the life of the copyright of the Composition and any and all renewals or extensions thereof, as provided by law.

4. Warranties and Representations.
Writer represents and warrants that:
(a) Writer is the sole author and composer of the Composition and has the full right, power, and authority to enter into this Agreement.
(b) The Composition is original and does not infringe upon any other copyrighted work.
(c) The writers contributing to this work are accurately represented as: [WRITER_NAMES].

5. Governing Law.
This Agreement shall be governed by and construed in accordance with the laws of the jurisdiction in which the Publisher's principal office is located.

IN WITNESS WHEREOF, the submission of the Composition via the Sap Media Publishing platform constitutes a binding agreement to the terms outlined above.

Electronically Signed by: [SUBMITTER_NAME]
IP Address: [SIGNING_IP_ADDRESS]
Date: [SUBMISSION_DATE]

Publisher: Sap Media Publishing
Writer: [SUBMITTER_NAME]
`;

export const USER_AGREEMENT_TEMPLATE = `
This Exclusive Writer and Publishing Agreement ("Agreement") is entered into as of [SIGNUP_DATE] ("Effective Date"), by and between Sap Media Publishing ("Publisher") and [USER_NAME] ("Writer").

WHEREAS, Writer is engaged in the business of writing and composing musical compositions; and
WHEREAS, Publisher has the resources and expertise to administer, exploit, and promote musical compositions;

NOW, THEREFORE, the parties agree as follows:

1. EXCLUSIVITY & TERM
Writer hereby agrees to render services exclusively to Publisher as a songwriter and composer for an initial period of two (2) years ("Initial Term") from the Effective Date. This agreement shall automatically renew for subsequent one (1) year periods unless terminated by either party with sixty (60) days written notice prior to the end of the current term.

2. GRANT OF RIGHTS
Writer hereby assigns, transfers, and grants to Publisher, for the entire world, all rights and interests of every kind and nature in and to one hundred percent (100%) of all musical compositions written or co-written by Writer during the Term of this Agreement (the "Compositions"), including the worldwide copyright thereof. This includes, but is not limited to, the right to:
(a) Register, administer, and protect the copyrights of the Compositions.
(b) License the Compositions for mechanical reproduction, public performance, synchronization, and all other uses.
(c) Collect all income and royalties generated by the Compositions.

3. ROYALTIES & INCOME SPLIT
Publisher shall collect all gross receipts derived from the Compositions. After deducting any and all third-party costs (such as co-writer shares, sample clearance fees, or collection society fees), the remaining "Net Income" shall be divided as follows:
(a) Fifty Percent (50%) to the Writer(s) share.
(b) Fifty Percent (50%) to the Publisher's share.

Publisher shall account for and pay all royalties to Writer on a semi-annual basis, within ninety (90) days following the end of each calendar half-year.

4. WARRANTIES
Writer warrants that they are the original author of the Compositions, that the Compositions are original and do not infringe on any third-party rights, and that Writer has the full authority to enter into this Agreement.

By creating an account and agreeing to these terms, Writer acknowledges they have read, understood, and agree to be bound by this Exclusive Writer and Publishing Agreement.

Publisher: Sap Media Publishing
Writer: [USER_NAME]
`;